default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tktter_development

test:
  <<: *default
  database: tktter_test

production:
  <<: *default
  database: tktter_production
  username: root
  password: 
